name: GitHub Pages deploy
on:
  push:
    branches:
      - master
jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
    - name: checkout
      uses: actions/checkout@master

    - name: setup node
      uses: actions/setup-node@v1
      with:
          node-version: '12.x'

    - name: install npm dependencies
      run: npm ci

    - name: build
      run: npm build

    - name: gh-pages deploy
      uses: Cecilapp/GitHub-Pages-deploy@master
      env:
        EMAIL: cowglow@gmail.com
        GH_TOKEN: ${{ secrets.ACCESS_TOKEN }}
        BUILD_DIR: public
