name: GitHub Pages deploy
on:
  push:
    branches:
      - master
jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - uses: actions/setup-node@v1
      with:
          node-version: '12.x'
    - run: npm ci
    - run: npm build
    - uses: Cecilapp/GitHub-Pages-deploy@master
      env:
        EMAIL: cowglow@gmail.com
        GH_TOKEN: ${{ secrets.ACCESS_TOKEN }}
        BUILD_DIR: public
